# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 19:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AbilityDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
                ('AbilityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('Index', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('JapaneseName', models.CharField(max_length=20)),
                ('Transliteration', models.CharField(max_length=20)),
                ('Romaji', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('HatchTime', models.PositiveIntegerField()),
                ('ExperienceYield', models.PositiveIntegerField()),
                ('CatchRate', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('GenderCode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('BaseFriendship', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='')),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Sprite', models.ImageField(upload_to='')),
                ('PokemonIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon')),
                ('Types', models.ManyToManyField(to='pokemon.Type')),
            ],
        ),
        migrations.CreateModel(
            name='VariationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='VariationType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.VariationTypes'),
        ),
        migrations.AddField(
            model_name='abilitydescription',
            name='GenerationName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Generation'),
        ),
    ]
